version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "04:00"
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "04:00"
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
